/**
 * PDF Report Generator — consumes the shared AnalysisResult.
 * Every section is dataset-specific. Sections are omitted if not applicable.
 * Uses proper pagination with content tracking to avoid overlaps.
 */

import jsPDF from 'jspdf';

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const CONTENT_BOTTOM = PAGE_HEIGHT - MARGIN - 20;

function prettifyName(name) {
  return name.replace(/[_-]+/g, ' ').replace(/\b\w/g, c => c.toUpperCase()).trim();
}

function formatDate(d) {
  return new Date(d).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

function formatNumber(n, fmt) {
  if (n === null || n === undefined || isNaN(n)) return '—';
  if (fmt === 'M') return `${(n / 1_000_000).toFixed(2)}M`;
  if (fmt === 'K') return `${(n / 1_000).toFixed(1)}K`;
  if (n % 1 === 0) return n.toLocaleString();
  return parseFloat(n.toFixed(2)).toLocaleString();
}

/**
 * Layout helper — tracks Y position and handles page breaks.
 */
class PDFLayout {
  constructor(doc) {
    this.doc = doc;
    this.y = MARGIN;
    this.pageNum = 1;
  }

  ensureSpace(needed) {
    if (this.y + needed > CONTENT_BOTTOM) {
      this.addPageBreak();
    }
  }

  addPageBreak() {
    this.addFooter();
    this.doc.addPage();
    this.pageNum++;
    this.y = MARGIN;
    this.addHeader();
  }

  addHeader() {
    this.doc.setFontSize(8);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text(`DataVision Analysis Report`, MARGIN, this.y - 10);
  this.doc.text(`Page ${this.pageNum}`, PAGE_WIDTH - MARGIN - 10, this.y - 10, { align: 'right' });
  }

  addFooter() {
    this.doc.setFontSize(8);
    this.doc.setTextColor(120, 120, 120);
    this.doc.text('Generated by DataVision AI Dashboard', MARGIN, PAGE_HEIGHT - 20);
    this.doc.text(`Page ${this.pageNum}`, PAGE_WIDTH - MARGIN - 10, PAGE_HEIGHT - 20, { align: 'right' });
  }

  sectionTitle(title) {
    this.ensureSpace(40);
    this.y += 10;
    this.doc.setFontSize(16);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setTextColor(30, 41, 59);
    this.doc.text(title, MARGIN, this.y);
    this.doc.setDrawColor(99, 102, 241);
    this.doc.setLineWidth(1.5);
    this.doc.line(MARGIN, this.y + 4, MARGIN + 40, this.y + 4);
    this.y += 24;
  }

  bodyText(text, opts = {}) {
    const fontSize = opts.fontSize || 11;
    const lineHeight = opts.lineHeight || 6;
    this.doc.setFontSize(fontSize);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(51, 65, 85);
    const lines = this.doc.splitTextToSize(text, CONTENT_WIDTH);
    for (const line of lines) {
      this.ensureSpace(lineHeight);
      this.doc.text(line, MARGIN, this.y);
      this.y += lineHeight;
    }
    this.y += 4;
  }

  bulletList(items) {
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'normal');
    this.doc.setTextColor(51, 65, 85);
    for (const item of items) {
      this.ensureSpace(12);
      this.doc.text('•', MARGIN, this.y);
      const lines = this.doc.splitTextToSize(item, CONTENT_WIDTH - 15);
      for (const line of lines) {
        this.ensureSpace(6);
        this.doc.text(line, MARGIN + 15, this.y);
        this.y += 6;
      }
      this.y += 2;
    }
  }

  table(headers, rows, colWidths) {
    const rowHeight = 14;
    // Header row
    this.ensureSpace(rowHeight);
    this.doc.setFontSize(10);
    this.doc.setFont('helvetica', 'bold');
    this.doc.setFillColor(99, 102, 241);
    this.doc.setTextColor(255, 255, 255);
    let x = MARGIN;
    headers.forEach((h, i) => {
      this.doc.setFillColor(99, 102, 241);
      this.doc.rect(x, this.y - 8, colWidths[i], rowHeight, 'F');
      this.doc.text(String(h).slice(0, 25), x + 4, this.y);
      x += colWidths[i];
    });
    this.y += rowHeight;

    // Data rows
    this.doc.setFontSize(9);
    this.doc.setFont('helvetica', 'normal');
    rows.forEach((row, rowIdx) => {
      this.ensureSpace(rowHeight);
      x = MARGIN;
      const isAlt = rowIdx % 2 === 0;
      this.doc.setFillColor(isAlt ? 248 : 255, isAlt ? 250 : 255, 252);
      this.doc.rect(MARGIN, this.y - 8, colWidths.reduce((a, b) => a + b, 0), rowHeight, 'F');
      this.doc.setTextColor(51, 65, 85);
      row.forEach((cell, i) => {
        this.doc.text(String(cell).slice(0, 30), x + 4, this.y);
        x += colWidths[i];
      });
      this.y += rowHeight;
    });
    this.y += 8;
  }

  kpiCards(kpis) {
    const cardWidth = (CONTENT_WIDTH - 16) / 3;
    const cardHeight = 50;
    const cardsPerRow = Math.min(kpis.length, 3);
    this.ensureSpace(cardHeight + 8);
    let x = MARGIN;
    kpis.slice(0, 6).forEach((kpi, i) => {
      if (i % 3 === 0) { x = MARGIN; this.ensureSpace(cardHeight + 8); }
      // Card background
      this.doc.setFillColor(245, 247, 250);
      this.doc.roundedRect(x, this.y, cardWidth, cardHeight, 4, 4, 'F');
      this.doc.setFillColor(99, 102, 241);
      this.doc.rect(x, this.y, 3, cardHeight, 'F');
      // Title
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(100, 116, 139);
      this.doc.text(kpi.title.slice(0, 25), x + 8, this.y + 12);
      // Value
      this.doc.setFontSize(18);
      this.doc.setFont('helvetica', 'bold');
      this.doc.setTextColor(30, 41, 59);
      this.doc.text(formatNumber(kpi.value, kpi.format), x + 8, this.y + 34);
      // Sub-stats
      this.doc.setFontSize(8);
      this.doc.setFont('helvetica', 'normal');
      this.doc.setTextColor(100, 116, 139);
      let subX = x + 8;
      if (kpi.avg != null) { this.doc.text(`Avg: ${formatNumber(kpi.avg, kpi.format)}`, subX, this.y + 44); subX += 50; }
      if (kpi.max != null) { this.doc.text(`Max: ${formatNumber(kpi.max, kpi.format)}`, subX, this.y + 44); subX += 50; }
      if (kpi.count != null) { this.doc.text(`Count: ${formatNumber(kpi.count, 'raw')}`, subX, this.y + 44); }
      x += cardWidth + 8;
      if ((i + 1) % 3 === 0) this.y += cardHeight + 8;
    });
    if (kpis.length % 3 !== 0) this.y += cardHeight + 8;
  }

  finish() {
    this.addFooter();
  }
}

/**
 * Generate a complete dataset-specific PDF report from the AnalysisResult.
 * @param {Object} dataset - dataset metadata { name, fileType, rowCount, columns, sample, preview }
 * @param {Object} analysisResult - shared AnalysisResult from the analysis engine
 * @param {Object} options - { filters, timeline }
 */
export async function generateAnalysisReport(dataset, analysisResult, options = {}) {
  const { filters = {}, timeline = null } = options;
  const analysis = analysisResult?.charts ? analysisResult : null;
  const charts = analysis?.charts || (Array.isArray(analysisResult) ? analysisResult : []);
  const result = analysis || {};

  const doc = new jsPDF('p', 'pt', 'a4');
  const layout = new PDFLayout(doc);

  const profile = result.datasetProfile || { name: dataset?.name, totalRows: dataset?.rowCount, totalColumns: dataset?.columns?.length || 0 };
  const classification = result.classification || {};
  const dataQuality = result.dataQuality || {};
  const kpis = result.kpis || [];
  const insights = result.insights || [];
  const recommendations = result.recommendations || [];
  const questions = result.questions || [];
  const statistics = result.statistics || {};
  const correlations = result.correlations || null;
  const timeSeries = result.timeSeries || null;
  const yearDistribution = result.yearDistribution || null;
  const segments = result.segments || {};
  const distributions = result.distributions || {};
  const columnProfiles = result.columnProfiles || [];

  // ── COVER PAGE ──
  doc.setFillColor(10, 13, 20);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, PAGE_WIDTH, 6, 'F');
  doc.setFillColor(6, 182, 212);
  doc.rect(0, 6, PAGE_WIDTH, 2, 'F');
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text('Data Analysis', MARGIN, 300);
  doc.text('Report', MARGIN, 340);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Dataset: ${dataset?.name || 'Untitled'}`, MARGIN, 380);
  doc.text(`Rows: ${profile.totalRows?.toLocaleString() || 'N/A'} | Columns: ${profile.totalColumns || 'N/A'}`, MARGIN, 400);
  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated: ${formatDate(new Date())}`, MARGIN, 430);
  if (timeline) doc.text(`Date Range: ${timeline.start} to ${timeline.end}`, MARGIN, 448);
  const activeFilters = Object.values(filters).filter(v => Array.isArray(v) && v.length > 0).length;
  if (activeFilters > 0) doc.text(`Active Filters: ${activeFilters} column(s) filtered`, MARGIN, 466);
  doc.setFontSize(10);
  doc.setTextColor(99, 102, 241);
  doc.text('DataVision AI Dashboard', MARGIN, PAGE_HEIGHT - 40);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('Automated EDA & Business Intelligence Report', MARGIN, PAGE_HEIGHT - 26);

  // ── EXECUTIVE SUMMARY ──
  doc.addPage();
  layout.pageNum = 2;
  layout.y = MARGIN;
  layout.addHeader();
  layout.sectionTitle('Executive Summary');

  const measuresCount = classification.measures?.length || 0;
  const dimensionsCount = classification.dimensions?.length || 0;
  const dateCount = classification.dateColumns?.length || 0;
  const idCount = classification.ids?.length || 0;

  const execText = `This report presents a comprehensive analysis of the "${dataset?.name}" dataset, containing ${profile.totalRows?.toLocaleString() || 'N/A'} records across ${profile.totalColumns || 'N/A'} columns. The analysis engine detected ${measuresCount} numeric measure(s), ${dimensionsCount} categorical dimension(s), ${dateCount} date/time column(s), and ${idCount} ID column(s). Data completeness is ${dataQuality.completenessPct?.toFixed(1) || 'N/A'}% with ${dataQuality.totalMissing?.toLocaleString() || 0} missing values identified.`;
  layout.bodyText(execText);

  if (kpis.length > 0) {
    layout.bodyText('Key Performance Indicators:', { fontSize: 11 });
    layout.kpiCards(kpis);
  }

  // ── DATASET OVERVIEW ──
  layout.sectionTitle('Dataset Overview');
  layout.bodyText(`The dataset "${dataset?.name}" was loaded from a ${dataset?.fileType?.toUpperCase() || 'data'} file containing ${profile.totalRows?.toLocaleString() || 'N/A'} rows and ${profile.totalColumns || 'N/A'} columns. The file size is approximately ${dataset?.sizeBytes ? (dataset.sizeBytes / 1024).toFixed(1) + ' KB' : 'N/A'}.`);
  layout.bodyText(`Column type distribution: ${measuresCount} numeric measure(s), ${dimensionsCount} categorical dimension(s), ${dateCount} date/time column(s), ${idCount} ID column(s), ${classification.geoColumns?.length || 0} geographic column(s), ${classification.booleans?.length || 0} boolean column(s).`);

  if (questions.length > 0) {
    layout.bodyText('Analytical Questions Identified:', { fontSize: 11 });
    layout.bulletList(questions);
  }

  // ── DATA DICTIONARY ──
  layout.sectionTitle('Data Dictionary');
  const ddWidths = [130, 70, 60, 60, 60, CONTENT_WIDTH - 380];
  layout.table(
    ['Column Name', 'Role', 'Type', 'Confidence', 'Unique', 'Missing %'],
    columnProfiles.map(p => [
      p.column.slice(0, 25),
      p.role,
      p.dataType,
      `${(p.confidence * 100).toFixed(0)}%`,
      p.uniqueCount?.toLocaleString() || '—',
      `${p.missingPct?.toFixed(1)}%`,
    ]),
    ddWidths
  );

  // ── DATA QUALITY ──
  layout.sectionTitle('Data Quality Analysis');
  layout.bodyText(`Overall quality score: ${dataQuality.qualityScore?.toFixed(1) || 'N/A'}/100. The dataset has ${dataQuality.totalMissing?.toLocaleString() || 0} missing values (${dataQuality.missingPct?.toFixed(2) || 0}%), ${dataQuality.duplicateRows?.toLocaleString() || 0} duplicate rows (${dataQuality.duplicatePct?.toFixed(2) || 0}%), ${dataQuality.constantColumns || 0} constant column(s), and ${dataQuality.highCardinalityColumns || 0} high-cardinality column(s).`);

  if (dataQuality.suspiciousColumns?.length > 0) {
    layout.bodyText('Quality Flags:', { fontSize: 11 });
    const dqWidths = [130, 100, 120, 80];
    layout.table(
      ['Column', 'Issue', 'Detail', 'Severity'],
      dataQuality.suspiciousColumns.map(s => [s.column.slice(0, 25), s.issue, s.detail, s.severity]),
      dqWidths
    );
  }

  // ── KPIs ──
  if (kpis.length > 0) {
    layout.sectionTitle('Key Performance Indicators');
    layout.bodyText('The following KPIs were selected based on the semantic analysis of the dataset. ID columns and year columns were excluded from aggregation.');
    layout.kpiCards(kpis);
    const kpiWidths = [180, 80, 80, 80, 80];
    layout.table(
      ['KPI', 'Value', 'Type', 'Confidence', 'Reason'],
      kpis.map(k => [k.title.slice(0, 30), formatNumber(k.value, k.format), k.displayType, `${(k.confidence * 100).toFixed(0)}%`, k.reason?.slice(0, 30) || '']),
      kpiWidths
    );
  }

  // ── UNIVARIATE ANALYSIS ──
  const statEntries = Object.entries(statistics);
  if (statEntries.length > 0) {
    layout.sectionTitle('Univariate Analysis — Numeric Measures');
    layout.bodyText('Statistical summary of numeric measure columns (ID and year columns excluded):');
    const statWidths = [100, 50, 50, 50, 50, 50, 50, 50];
    layout.table(
      ['Column', 'Mean', 'Median', 'Std', 'Min', 'Max', 'Q1', 'Q3'],
      statEntries.map(([col, s]) => [
        col.slice(0, 20), s.mean.toFixed(2), s.median.toFixed(2), s.std.toFixed(2),
        s.min.toFixed(2), s.max.toFixed(2), s.q1.toFixed(2), s.q3.toFixed(2),
      ]),
      statWidths
    );

    // Outlier summary
    const outlierCols = statEntries.filter(([, s]) => s.hasOutliers);
    if (outlierCols.length > 0) {
      layout.bodyText('Outlier Detection (IQR Method):', { fontSize: 11 });
      layout.bulletList(outlierCols.map(([col, s]) =>
        `${prettifyName(col)}: ${s.outlierCount} outlier(s) (${s.outlierPct}%), IQR range: ${s.q1.toFixed(2)}–${s.q3.toFixed(2)}`
      ));
    }
  }

  // Categorical distributions
  const distEntries = Object.entries(distributions);
  if (distEntries.length > 0) {
    layout.sectionTitle('Univariate Analysis — Categorical Dimensions');
    for (const [col, dist] of distEntries.slice(0, 5)) {
      layout.bodyText(`${prettifyName(col)}: ${dist.totalCategories} unique value(s)${dist.nullCount > 0 ? `, ${dist.nullCount} missing` : ''}.`, { fontSize: 11 });
      if (dist.categories?.length > 0) {
        const catWidths = [180, 60, 60];
        layout.table(
          ['Value', 'Count', '%'],
          dist.categories.slice(0, 10).map(c => [String(c.value).slice(0, 30), c.count.toLocaleString(), `${c.pct}%`]),
          catWidths
        );
      }
    }
  }

  // ── BIVARIATE ANALYSIS ──
  if (correlations?.significantPairs?.length > 0) {
    layout.sectionTitle('Bivariate Analysis — Correlations');
    layout.bodyText('Pearson correlation coefficients between numeric measure columns. Only correlations with |r| >= 0.3 are shown. Correlation does not imply causation.');
    const corrWidths = [150, 150, 60, 60, 60];
    layout.table(
      ['Column A', 'Column B', 'r', 'Strength', 'Direction'],
      correlations.significantPairs.map(p => [p.colA.slice(0, 25), p.colB.slice(0, 25), p.correlation.toFixed(3), p.strength, p.direction]),
      corrWidths
    );
  }

  // ── TIME SERIES ANALYSIS ──
  if (timeSeries?.data?.length > 1) {
    layout.sectionTitle('Time Series Analysis');
    const dateCol = timeSeries.column;
    const measureCol = timeSeries.measure;
    layout.bodyText(`Trend analysis using ${prettifyName(dateCol)} as the time dimension${measureCol ? ` and ${prettifyName(measureCol)} as the measure` : ' with record count as the measure'}.`);

    const tsData = timeSeries.data;
    const first = tsData[0];
    const last = tsData[tsData.length - 1];
    const firstVal = measureCol ? first[measureCol] : first.count;
    const lastVal = measureCol ? last[measureCol] : last.count;
    if (firstVal !== 0) {
      const change = ((lastVal - firstVal) / Math.abs(firstVal)) * 100;
      layout.bodyText(`From ${first.date} to ${last.date}, the value ${change >= 0 ? 'increased' : 'decreased'} from ${firstVal.toLocaleString()} to ${lastVal.toLocaleString()} (${change >= 0 ? '+' : ''}${change.toFixed(1)}%).`);
    }

    const tsWidths = [120, 80, 80];
    layout.table(
      ['Date', measureCol ? prettifyName(measureCol) : 'Count', 'Records'],
      tsData.slice(0, 20).map(d => [d.date, (measureCol ? d[measureCol] : d.count)?.toLocaleString(), d.count?.toLocaleString()]),
      tsWidths
    );
  }

  // ── YEAR DISTRIBUTION ──
  if (yearDistribution?.data?.length > 1) {
    layout.sectionTitle('Year Distribution Analysis');
    layout.bodyText(`Distribution of records by ${prettifyName(yearDistribution.column)}. This column was detected as a YEAR type — record counts per year are shown (not sums of year values).`);
    const yrWidths = [80, 80, 80];
    layout.table(
      ['Year', 'Count', '%'],
      yearDistribution.data.map(d => [String(d.year), d.count.toLocaleString(), `${d.pct}%`]),
      yrWidths
    );
  }

  // ── SEGMENT ANALYSIS ──
  const segEntries = Object.entries(segments);
  if (segEntries.length > 0) {
    layout.sectionTitle('Category / Segment Analysis');
    for (const [col, segData] of segEntries.slice(0, 3)) {
      if (segData.length === 0) continue;
      const measureKey = Object.keys(segData[0]).find(k => k !== col && k !== 'count' && k !== 'pct' && k !== 'mean' && k !== 'min' && k !== 'max');
      layout.bodyText(`${prettifyName(col)} — ${measureKey ? `by ${prettifyName(measureKey)}` : 'by record count'}:`, { fontSize: 11 });
      const segWidths = [150, 70, 70, 70];
      layout.table(
        [prettifyName(col), measureKey ? 'Sum' : 'Count', 'Count', 'Mean'],
        segData.slice(0, 10).map(s => [
          String(s[col]).slice(0, 25),
          (measureKey ? s[measureKey] : s.count)?.toLocaleString(),
          s.count?.toLocaleString(),
          s.mean != null ? s.mean.toFixed(2) : '—',
        ]),
        segWidths
      );
    }
  }

  // ── VISUAL ANALYSIS (chart descriptions) ──
  const nonKpiCharts = charts.filter(c => c.type !== 'kpi');
  if (nonKpiCharts.length > 0) {
    layout.sectionTitle('Visual Analysis');
    layout.bodyText('The following visualizations were selected based on column roles, cardinality, and relationships:');
    for (const chart of nonKpiCharts) {
      if (chart.explanation) {
        layout.bodyText(`${chart.title} (${chart.type})`, { fontSize: 11 });
        layout.bodyText(`What: ${chart.explanation.what}`);
        layout.bodyText(`Why: ${chart.explanation.why}`);
        layout.bodyText(`Insight: ${chart.explanation.insight}`);
        layout.y += 4;
      }
    }
  }

  // ── KEY INSIGHTS ──
  if (insights.length > 0) {
    layout.sectionTitle('Key Insights');
    layout.bulletList(insights.map(i => `${i.title}: ${i.body}`));
  }

  // ── RECOMMENDATIONS ──
  if (recommendations.length > 0) {
    layout.sectionTitle('Business / Analytical Recommendations');
    layout.bodyText('The following recommendations are derived from the actual analytical findings above:');
    for (const rec of recommendations) {
      layout.bodyText(`${rec.title}`, { fontSize: 11 });
      layout.bodyText(rec.body);
      if (rec.basedOn) layout.bodyText(`Based on: ${rec.basedOn}`, { fontSize: 9 });
      layout.y += 4;
    }
  }

  // ── CONCLUSION ──
  layout.sectionTitle('Conclusion');
  const conclusionText = `This analysis of the "${dataset?.name}" dataset revealed ${insights.length} key insight(s) and ${recommendations.length} recommendation(s). The dataset contains ${profile.totalRows?.toLocaleString() || 'N/A'} records with a data quality score of ${dataQuality.qualityScore?.toFixed(1) || 'N/A'}/100. ${measuresCount > 0 ? `${measuresCount} numeric measure(s) were analyzed statistically.` : 'No numeric measures were found.'} ${dateCount > 0 ? 'Time series analysis was performed.' : 'No date columns were available for trend analysis.'} ${correlations?.significantPairs?.length > 0 ? `${correlations.significantPairs.length} significant correlation(s) were detected.` : 'No significant correlations were found.'}`;
  layout.bodyText(conclusionText);

  // ── LIMITATIONS ──
  layout.sectionTitle('Limitations');
  const limitations = [
    `Analysis is based on a sample of ${profile.sampleSize?.toLocaleString() || 'N/A'} rows from ${profile.totalRows?.toLocaleString() || 'N/A'} total records.`,
    'Pearson correlation measures linear relationships only and does not capture non-linear patterns.',
    'Correlation does not imply causation; further investigation is needed for causal claims.',
  ];
  if (dateCount === 0) limitations.push('No date/time columns were available, limiting temporal analysis.');
  if (measuresCount < 2) limitations.push('Fewer than 2 numeric measures were available, limiting bivariate analysis.');
  layout.bulletList(limitations);

  // ── FUTURE SCOPE ──
  layout.sectionTitle('Future Scope');
  layout.bulletList([
    'Expand the analysis with additional data sources for richer context.',
    'Apply machine learning models for predictive analytics once more historical data is available.',
    'Implement automated monitoring to track changes in key metrics over time.',
    'Conduct deeper segment-level analysis with additional dimensions.',
  ]);

  // ── APPENDIX ──
  layout.sectionTitle('Appendix — Column Profiles');
  const apWidths = [130, 70, 50, 50, 50, 50, CONTENT_WIDTH - 400];
  layout.table(
    ['Column', 'Role', 'Type', 'Unique', 'Missing', 'Cardinality', 'Signals'],
    columnProfiles.map(p => [
      p.column.slice(0, 25), p.role, p.dataType,
      p.uniqueCount?.toLocaleString() || '—', `${p.missingPct?.toFixed(1)}%`,
      p.cardinalityRatio != null ? p.cardinalityRatio.toFixed(3) : '—',
      (p.signals || []).join('; ').slice(0, 40),
    ]),
    apWidths
  );

  layout.finish();
  doc.save(`DataVision_Report_${dataset?.name || 'Dataset'}.pdf`);
}
