// Comprehensive PDF Analysis Report Generator
// Uses jsPDF to build a multi-page analysis report from dataset + dashboard charts.

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { formatNumber, aggregateBy } from './aiSuggester';

const PAGE_WIDTH = 595; // A4 in pt
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;

function formatDate(d) {
  return new Date(d).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

function addPageNumber(doc, pageNum) {
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(`Page ${pageNum}`, PAGE_WIDTH - MARGIN - 10, PAGE_HEIGHT - 20, {
    align: 'right',
  });
}

function addFooter(doc) {
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(
    'Generated by DataVision AI Dashboard',
    MARGIN,
    PAGE_HEIGHT - 20
  );
}

function sectionTitle(doc, title, y, pageNum) {
  doc.setFontSize(16);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text(title, MARGIN, y);
  // underline
  doc.setDrawColor(99, 102, 241);
  doc.setLineWidth(1.5);
  doc.line(MARGIN, y + 4, MARGIN + 40, y + 4);
  addPageNumber(doc, pageNum);
  return y + 20;
}

function bodyText(doc, text, y, options = {}) {
  const fontSize = options.fontSize || 11;
  const lineHeight = options.lineHeight || 6;
  doc.setFontSize(fontSize);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  const lines = doc.splitTextToSize(text, CONTENT_WIDTH);
  lines.forEach((line) => {
    if (y > PAGE_HEIGHT - MARGIN - 10) {
      doc.addPage();
      y = MARGIN;
    }
    doc.text(line, MARGIN, y);
    y += lineHeight;
  });
  return y + 4;
}

function bulletList(doc, items, y, pageNum) {
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(51, 65, 85);
  items.forEach((item) => {
    if (y > PAGE_HEIGHT - MARGIN - 10) {
      doc.addPage();
      y = MARGIN;
      addPageNumber(doc, pageNum);
    }
    doc.text('•', MARGIN, y);
    const lines = doc.splitTextToSize(item, CONTENT_WIDTH - 15);
    lines.forEach((line) => {
      doc.text(line, MARGIN + 15, y);
      y += 6;
    });
    y += 2;
  });
  return y;
}

function tableRow(doc, row, y, colWidths, isHeader) {
  doc.setFontSize(isHeader ? 10 : 9);
  doc.setFont('helvetica', isHeader ? 'bold' : 'normal');
  if (isHeader) {
    doc.setFillColor(99, 102, 241);
    doc.setTextColor(255, 255, 255);
  } else {
    doc.setTextColor(51, 65, 85);
    doc.setFillColor(y % 12 === 0 ? 248 : 255, 250, 252);
  }
  let x = MARGIN;
  row.forEach((cell, i) => {
    doc.setFillColor(isHeader ? 99 : 250, isHeader ? 102 : 252, isHeader ? 241 : 252);
    doc.rect(x, y - 8, colWidths[i], 14, 'F');
    doc.text(String(cell).slice(0, 30), x + 4, y);
    x += colWidths[i];
  });
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  x = MARGIN;
  row.forEach((_, i) => {
    doc.line(x, y - 8, x, y + 6);
    x += colWidths[i];
  });
  doc.line(MARGIN, y + 6, MARGIN + colWidths.reduce((a, b) => a + b, 0), y + 6);
  return y + 14;
}

/**
 * Main report generation function.
 * @param {Object} dataset - { name, schema, data, rowCount, columnCount, fileType }
 * @param {Array} charts - dashboard chart configs
 * @param {Object} options - { filters, timeline, reportDate }
 */
export async function generateAnalysisReport(dataset, charts, options = {}) {
  const { filters = {}, timeline = null } = options;
  const doc = new jsPDF('p', 'pt', 'a4');
  let pageNum = 1;
  let y = MARGIN;

  const schema = dataset?.schema || [];
  const data = dataset?.data || [];
  const numericCols = schema.filter((c) => c.type === 'numeric');
  const categoryCols = schema.filter((c) => c.type === 'category' || c.type === 'text');
  const dateCols = schema.filter((c) => c.type === 'date');

  // ── COVER PAGE ──
  // Background
  doc.setFillColor(10, 13, 20);
  doc.rect(0, 0, PAGE_WIDTH, PAGE_HEIGHT, 'F');

  // Accent bar
  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, PAGE_WIDTH, 6, 'F');
  doc.setFillColor(6, 182, 212);
  doc.rect(0, 6, PAGE_WIDTH, 2, 'F');

  // Title
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text('Data Analysis', MARGIN, 300);
  doc.text('Report', MARGIN, 340);

  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(148, 163, 184);
  doc.text(`Dataset: ${dataset?.name || 'Untitled'}`, MARGIN, 380);
  doc.text(`Rows: ${dataset?.rowCount?.toLocaleString() || data.length} | Columns: ${dataset?.columnCount || schema.length}`, MARGIN, 400);

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text(`Generated: ${formatDate(new Date())}`, MARGIN, 430);
  if (timeline) {
    doc.text(`Date Range: ${timeline.start} to ${timeline.end}`, MARGIN, 448);
  }
  const activeFilters = Object.values(filters).filter((v) => Array.isArray(v) && v.length > 0).length;
  if (activeFilters > 0) {
    doc.text(`Active Filters: ${activeFilters} column(s) filtered`, MARGIN, 466);
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(99, 102, 241);
  doc.text('DataVision AI Dashboard', MARGIN, PAGE_HEIGHT - 40);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('Automated EDA & Business Intelligence Report', MARGIN, PAGE_HEIGHT - 26);

  // ── EXECUTIVE SUMMARY ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Executive Summary', y, pageNum);

  const totalRows = data.length;
  const totalCols = schema.length;
  const nullCounts = schema.reduce((sum, c) => sum + (c.nullCount || 0), 0);
  const completeness = totalRows > 0 ? (((totalRows * totalCols - nullCounts) / (totalRows * totalCols)) * 100).toFixed(1) : 100;

  const execSummary = `This report presents a comprehensive analysis of the "${dataset?.name}" dataset, containing ${totalRows.toLocaleString()} records across ${totalCols} columns. The dataset comprises ${numericCols.length} numeric, ${categoryCols.length} categorical, and ${dateCols.length} date/time variables. Overall data completeness is ${completeness}%, with ${nullCounts.toLocaleString()} missing values identified across all columns. The analysis covers exploratory data analysis, key performance indicators, univariate and multivariate analysis, trend detection, and segment-level insights, concluding with actionable business recommendations and future scope for deeper investigation.`;
  y = bodyText(doc, execSummary, y);

  y += 6;
  y = bodyText(doc, 'Key highlights:', y, { fontSize: 11 });
  const highlights = [];
  numericCols.slice(0, 3).forEach((col) => {
    const values = data.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
    if (values.length > 0) {
      const total = values.reduce((a, b) => a + b, 0);
      const avg = total / values.length;
      highlights.push(`${col.key}: Total ${formatNumber(total)}, Average ${formatNumber(avg)}, Max ${formatNumber(Math.max(...values))}, Min ${formatNumber(Math.min(...values))}`);
    }
  });
  categoryCols.slice(0, 2).forEach((col) => {
    const freq = {};
    data.forEach((r) => {
      const v = String(r[col.key] || '');
      if (v) freq[v] = (freq[v] || 0) + 1;
    });
    const top = Object.entries(freq).sort((a, b) => b[1] - a[1])[0];
    if (top) {
      highlights.push(`${col.key}: Most frequent value is "${top[0]}" (${((top[1] / totalRows) * 100).toFixed(1)}% of records)`);
    }
  });
  y = bulletList(doc, highlights, y, pageNum);

  // ── INTRODUCTION ──
  if (y > PAGE_HEIGHT - 200) { doc.addPage(); pageNum++; y = MARGIN; }
  y += 10;
  y = sectionTitle(doc, 'Introduction', y, pageNum);
  y = bodyText(doc, `This document provides a detailed analytical report on the "${dataset?.name}" dataset. The purpose is to transform raw data into meaningful insights through systematic exploration, statistical analysis, and visual interpretation. The report follows a structured methodology commonly used in data science and business analytics, covering data understanding, cleaning, exploratory analysis, and actionable recommendations.`, y);
  y = bodyText(doc, `The dataset was loaded from a ${dataset?.fileType?.toUpperCase() || 'data'} file containing ${totalRows.toLocaleString()} rows and ${totalCols} columns. The analysis was performed using the DataVision AI Dashboard platform, which automatically detects column types, generates visualizations, and computes statistical summaries.`, y);

  // ── BUSINESS PROBLEM ──
  if (y > PAGE_HEIGHT - 150) { doc.addPage(); pageNum++; y = MARGIN; }
  y += 10;
  y = sectionTitle(doc, 'Business Problem', y, pageNum);
  y = bodyText(doc, `The primary business problem addressed by this analysis is understanding the patterns, trends, and relationships within the "${dataset?.name}" data. Organizations need to extract actionable insights from their data to support decision-making, identify growth opportunities, optimize operations, and mitigate risks. This report aims to answer key questions such as: What are the dominant categories? How do key metrics distribute? Are there significant trends over time? Which segments drive the most value?`, y);

  // ── OBJECTIVES ──
  if (y > PAGE_HEIGHT - 150) { doc.addPage(); pageNum++; y = MARGIN; }
  y += 10;
  y = sectionTitle(doc, 'Objectives', y, pageNum);
  y = bodyText(doc, 'The specific objectives of this analysis are:', y);
  y = bulletList(doc, [
    'Perform exploratory data analysis (EDA) to understand data distribution and structure.',
    'Identify and quantify key performance indicators (KPIs) relevant to the dataset.',
    'Conduct univariate, bivariate, and multivariate analysis to uncover relationships.',
    'Detect temporal trends and patterns using time-based analysis.',
    'Compare performance across categories and segments.',
    'Generate data visualizations for intuitive understanding.',
    'Derive actionable business recommendations from analytical findings.',
  ], y, pageNum);

  // ── DATASET INFORMATION ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Dataset Information', y, pageNum);
  y = bodyText(doc, `The dataset "${dataset?.name}" contains ${totalRows.toLocaleString()} records and ${totalCols} columns. The file format is ${dataset?.fileType?.toUpperCase() || 'unknown'}, with a file size of approximately ${dataset?.sizeBytes ? (dataset.sizeBytes / 1024).toFixed(1) + ' KB' : 'N/A'}.`, y);
  y = bodyText(doc, `Column type distribution: ${numericCols.length} numeric columns, ${categoryCols.length} categorical/text columns, and ${dateCols.length} date/time columns. Data completeness is ${completeness}%.`, y);

  // ── DATA DICTIONARY ──
  y += 10;
  y = sectionTitle(doc, 'Data Dictionary', y, pageNum);
  const ddColWidths = [120, 60, 80, 80, CONTENT_WIDTH - 340];
  y = tableRow(doc, ['Column Name', 'Type', 'Min', 'Max', 'Null Count'], y, ddColWidths, true);
  schema.forEach((col) => {
    if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = tableRow(doc, [
      col.key,
      col.type,
      col.min !== null ? formatNumber(col.min) : '—',
      col.max !== null ? formatNumber(col.max) : '—',
      String(col.nullCount || 0),
    ], y, ddColWidths, false);
  });

  // ── DATA CLEANING & PREPROCESSING ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Data Cleaning & Preprocessing', y, pageNum);
  y = bodyText(doc, 'The following data cleaning and preprocessing steps were applied:', y);
  const cleaningSteps = [
    `Column type detection: Each column was automatically classified as numeric, category, text, or date based on value analysis.`,
    `Missing value identification: ${nullCounts.toLocaleString()} missing/null values were detected across all columns (${(100 - completeness).toFixed(1)}% of total cells).`,
    `Data validation: Numeric columns were validated for parse-ability; date columns were checked for valid date formats.`,
    `Schema analysis: Unique values, min/max ranges, and averages were computed for applicable columns.`,
  ];
  if (activeFilters > 0) {
    cleaningSteps.push(`Filtering: ${activeFilters} column(s) were filtered based on user-selected values before analysis.`);
  }
  if (timeline) {
    cleaningSteps.push(`Date range filtering: Data was restricted to the period ${timeline.start} through ${timeline.end}.`);
  }
  y = bulletList(doc, cleaningSteps, y, pageNum);

  // ── EXPLORATORY DATA ANALYSIS (EDA) ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Exploratory Data Analysis (EDA)', y, pageNum);
  y = bodyText(doc, `Exploratory Data Analysis was conducted to understand the underlying structure of the dataset. The EDA process involved examining the distribution of each variable, identifying outliers, detecting patterns, and exploring relationships between variables. The dataset contains ${totalRows.toLocaleString()} observations, which provides a sufficient sample size for meaningful statistical analysis.`, y);
  y = bodyText(doc, `The analysis began with univariate examination of each variable, followed by bivariate analysis to explore pairwise relationships, and finally multivariate analysis to understand complex interactions. Key statistical measures including mean, median, standard deviation, minimum, maximum, and quartiles were computed for all numeric variables.`, y);

  // ── KEY PERFORMANCE INDICATORS (KPIs) ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Key Performance Indicators (KPIs)', y, pageNum);
  const kpiCharts = charts.filter((c) => c.type === 'kpi');
  if (kpiCharts.length > 0) {
    y = bodyText(doc, 'The following key performance indicators were identified and measured:', y);
    const kpiItems = kpiCharts.map((kpi) => {
      const trendStr = kpi.trend !== undefined ? ` (Trend: ${kpi.trend > 0 ? '+' : ''}${kpi.trend}%)` : '';
      return `${kpi.title}: ${formatNumber(kpi.value, kpi.format)}${trendStr}. Average: ${formatNumber(kpi.avg, kpi.format)}, Maximum: ${formatNumber(kpi.max, kpi.format)}, Count: ${kpi.count || 'N/A'}.`;
    });
    y = bulletList(doc, kpiItems, y, pageNum);
  } else {
    y = bodyText(doc, 'No KPI cards were configured for this dashboard. Key numeric metrics are summarized below.', y);
    const kpiItems = numericCols.slice(0, 4).map((col) => {
      const values = data.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
      if (values.length === 0) return `${col.key}: No valid numeric data.`;
      const total = values.reduce((a, b) => a + b, 0);
      const avg = total / values.length;
      return `${col.key}: Total ${formatNumber(total)}, Average ${formatNumber(avg)}, Max ${formatNumber(Math.max(...values))}, Min ${formatNumber(Math.min(...values))}`;
    });
    y = bulletList(doc, kpiItems, y, pageNum);
  }

  // ── UNIVARIATE ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Univariate Analysis', y, pageNum);
  y = bodyText(doc, 'Univariate analysis examines each variable individually to understand its distribution, central tendency, and spread.', y);
  y += 4;

  // Numeric univariate
  if (numericCols.length > 0) {
    y = bodyText(doc, 'Numeric Variables:', y, { fontSize: 12 });
    const uniColWidths = [100, 65, 65, 65, 65, CONTENT_WIDTH - 360];
    y = tableRow(doc, ['Column', 'Mean', 'Min', 'Max', 'Std Dev', 'Range'], y, uniColWidths, true);
    numericCols.slice(0, 10).forEach((col) => {
      if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
      const values = data.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
      if (values.length === 0) return;
      const mean = values.reduce((a, b) => a + b, 0) / values.length;
      const std = Math.sqrt(values.map((v) => (v - mean) ** 2).reduce((a, b) => a + b, 0) / values.length);
      y = tableRow(doc, [
        col.key.slice(0, 18),
        formatNumber(mean),
        formatNumber(Math.min(...values)),
        formatNumber(Math.max(...values)),
        formatNumber(std),
        formatNumber(Math.max(...values) - Math.min(...values)),
      ], y, uniColWidths, false);
    });
  }

  y += 10;
  if (categoryCols.length > 0) {
    if (y > PAGE_HEIGHT - 200) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = bodyText(doc, 'Categorical Variables:', y, { fontSize: 12 });
    const catItems = categoryCols.slice(0, 5).map((col) => {
      const freq = {};
      data.forEach((r) => {
        const v = String(r[col.key] || 'N/A');
        freq[v] = (freq[v] || 0) + 1;
      });
      const entries = Object.entries(freq).sort((a, b) => b[1] - a[1]);
      const unique = entries.length;
      const top = entries[0] || ['N/A', 0];
      return `${col.key}: ${unique} unique values. Most frequent: "${top[0]}" (${((top[1] / totalRows) * 100).toFixed(1)}%)`;
    });
    y = bulletList(doc, catItems, y, pageNum);
  }

  // ── BIVARIATE ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Bivariate Analysis', y, pageNum);
  y = bodyText(doc, 'Bivariate analysis explores relationships between pairs of variables to identify correlations, dependencies, and comparative patterns.', y);
  y += 4;

  if (categoryCols.length > 0 && numericCols.length > 0) {
    y = bodyText(doc, 'Category vs. Numeric Analysis:', y, { fontSize: 12 });
    const catCol = categoryCols[0];
    const numCol = numericCols[0];
    const agg = aggregateBy(data, catCol.key, numCol.key);
    y = bodyText(doc, `Aggregation of ${numCol.key} by ${catCol.key} (top categories):`, y, { fontSize: 10 });
    const biColWidths = [180, 100, CONTENT_WIDTH - 280];
    y = tableRow(doc, [catCol.key, numCol.key + ' (Sum)', 'Share %'], y, biColWidths, true);
    const grandTotal = agg.reduce((s, r) => s + (r[numCol.key] || 0), 0);
    agg.slice(0, 10).forEach((row) => {
      if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
      const pct = grandTotal > 0 ? ((row[numCol.key] / grandTotal) * 100).toFixed(1) + '%' : '—';
      y = tableRow(doc, [String(row[catCol.key]).slice(0, 25), formatNumber(row[numCol.key]), pct], y, biColWidths, false);
    });
  }

  if (numericCols.length >= 2) {
    y += 10;
    if (y > PAGE_HEIGHT - 150) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = bodyText(doc, 'Numeric vs. Numeric Correlation:', y, { fontSize: 12 });
    const c1 = numericCols[0];
    const c2 = numericCols[1];
    const pairs = data.map((r) => [parseFloat(r[c1.key]), parseFloat(r[c2.key])]).filter(([a, b]) => !isNaN(a) && !isNaN(b));
    if (pairs.length > 5) {
      const mean1 = pairs.reduce((s, p) => s + p[0], 0) / pairs.length;
      const mean2 = pairs.reduce((s, p) => s + p[1], 0) / pairs.length;
      const cov = pairs.reduce((s, p) => s + (p[0] - mean1) * (p[1] - mean2), 0) / pairs.length;
      const std1 = Math.sqrt(pairs.reduce((s, p) => s + (p[0] - mean1) ** 2, 0) / pairs.length);
      const std2 = Math.sqrt(pairs.reduce((s, p) => s + (p[1] - mean2) ** 2, 0) / pairs.length);
      const corr = std1 > 0 && std2 > 0 ? cov / (std1 * std2) : 0;
      const strength = Math.abs(corr) > 0.7 ? 'strong' : Math.abs(corr) > 0.4 ? 'moderate' : 'weak';
      const direction = corr > 0 ? 'positive' : 'negative';
      y = bodyText(doc, `Pearson correlation between ${c1.key} and ${c2.key}: r = ${corr.toFixed(3)}, indicating a ${strength} ${direction} correlation based on ${pairs.length} paired observations.`, y);
    }
  }

  // ── MULTIVARIATE ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Multivariate Analysis', y, pageNum);
  y = bodyText(doc, 'Multivariate analysis examines the interactions among three or more variables simultaneously to uncover complex patterns.', y);
  y += 4;

  if (numericCols.length >= 3) {
    y = bodyText(doc, 'Correlation Matrix (Numeric Variables):', y, { fontSize: 12 });
    const corrCols = numericCols.slice(0, 5);
    const cmColWidth = CONTENT_WIDTH / (corrCols.length + 1);
    const cmColWidths = [cmColWidth, ...corrCols.map(() => cmColWidth)];
    y = tableRow(doc, ['', ...corrCols.map((c) => c.key.slice(0, 8))], y, cmColWidths, true);
    corrCols.forEach((rowCol, ri) => {
      if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
      const row = [rowCol.key.slice(0, 8)];
      corrCols.forEach((colCol, ci) => {
        if (ri === ci) {
          row.push('1.00');
        } else {
          const pairs = data.map((r) => [parseFloat(r[rowCol.key]), parseFloat(r[colCol.key])]).filter(([a, b]) => !isNaN(a) && !isNaN(b));
          if (pairs.length > 5) {
            const m1 = pairs.reduce((s, p) => s + p[0], 0) / pairs.length;
            const m2 = pairs.reduce((s, p) => s + p[1], 0) / pairs.length;
            const cov = pairs.reduce((s, p) => s + (p[0] - m1) * (p[1] - m2), 0) / pairs.length;
            const s1 = Math.sqrt(pairs.reduce((s, p) => s + (p[0] - m1) ** 2, 0) / pairs.length);
            const s2 = Math.sqrt(pairs.reduce((s, p) => s + (p[1] - m2) ** 2, 0) / pairs.length);
            row.push(s1 > 0 && s2 > 0 ? (cov / (s1 * s2)).toFixed(2) : '—');
          } else {
            row.push('—');
          }
        }
      });
      y = tableRow(doc, row, y, cmColWidths, false);
    });
  }

  y += 10;
  if (categoryCols.length >= 2 && numericCols.length >= 1) {
    if (y > PAGE_HEIGHT - 150) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = bodyText(doc, 'Cross-Category Analysis:', y, { fontSize: 12 });
    const cat1 = categoryCols[0];
    const cat2 = categoryCols[1];
    const numCol = numericCols[0];
    y = bodyText(doc, `A cross-tabulation of ${cat1.key} against ${cat2.key} (measured by ${numCol.key}) reveals how the key metric varies across combined segments. This helps identify which intersection of categories contributes most to the total.`, y);
  }

  // ── TREND ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Trend Analysis', y, pageNum);

  if (dateCols.length > 0 && numericCols.length > 0) {
    const dateCol = dateCols[0];
    y = bodyText(doc, `Temporal trend analysis was performed using the "${dateCol.key}" column as the time dimension. The following trends were observed:`, y);
    const trendItems = numericCols.slice(0, 3).map((col) => {
      const sorted = [...data].sort((a, b) => new Date(a[dateCol.key]) - new Date(b[dateCol.key]));
      const values = sorted.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
      if (values.length < 4) return `${col.key}: Insufficient data for trend analysis.`;
      const mid = Math.floor(values.length / 2);
      const firstHalf = values.slice(0, mid).reduce((a, b) => a + b, 0) / mid;
      const secondHalf = values.slice(mid).reduce((a, b) => a + b, 0) / (values.length - mid);
      const change = firstHalf !== 0 ? ((secondHalf - firstHalf) / Math.abs(firstHalf)) * 100 : 0;
      const direction = change > 5 ? 'upward' : change < -5 ? 'downward' : 'stable';
      return `${col.key}: ${direction.charAt(0).toUpperCase() + direction.slice(1)} trend with ${Math.abs(change).toFixed(1)}% change between first and second half of the time period. First-half average: ${formatNumber(firstHalf)}, Second-half average: ${formatNumber(secondHalf)}.`;
    });
    y = bulletList(doc, trendItems, y, pageNum);
  } else if (categoryCols.length > 0) {
    y = bodyText(doc, 'No date column was detected in the dataset. However, trend-like patterns were analyzed using the first categorical column as a sequential dimension:', y);
    const catCol = categoryCols[0];
    const trendItems = numericCols.slice(0, 2).map((col) => {
      const agg = aggregateBy(data, catCol.key, col.key);
      if (agg.length < 2) return `${col.key}: Insufficient data.`;
      const first = agg[agg.length - 1][col.key];
      const last = agg[0][col.key];
      const change = first !== 0 ? ((last - first) / Math.abs(first)) * 100 : 0;
      return `${col.key}: ${change > 0 ? 'Increase' : 'Decrease'} of ${Math.abs(change).toFixed(1)}% from "${agg[agg.length - 1][catCol.key]}" to "${agg[0][catCol.key]}".`;
    });
    y = bulletList(doc, trendItems, y, pageNum);
  } else {
    y = bodyText(doc, 'No date or category columns were found for trend analysis.', y);
  }

  // ── CATEGORY / SEGMENT ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Category / Segment Analysis', y, pageNum);
  y = bodyText(doc, 'Segment-level analysis breaks down key metrics by categorical dimensions to identify high- and low-performing groups.', y);
  y += 4;

  categoryCols.slice(0, 3).forEach((catCol) => {
    if (y > PAGE_HEIGHT - 200) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = bodyText(doc, `Segmentation by ${catCol.key}:`, y, { fontSize: 12 });
    const numCol = numericCols[0];
    if (!numCol) {
      y = bodyText(doc, 'No numeric column available for segment comparison.', y);
      return;
    }
    const agg = aggregateBy(data, catCol.key, numCol.key);
    const segColWidths = [180, 80, 80, CONTENT_WIDTH - 340];
    y = tableRow(doc, [catCol.key, numCol.key, 'Count', 'Share %'], y, segColWidths, true);
    const grandTotal = agg.reduce((s, r) => s + (r[numCol.key] || 0), 0);
    agg.slice(0, 8).forEach((row) => {
      if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
      const pct = grandTotal > 0 ? ((row[numCol.key] / grandTotal) * 100).toFixed(1) + '%' : '—';
      y = tableRow(doc, [String(row[catCol.key]).slice(0, 25), formatNumber(row[numCol.key]), String(row.count || ''), pct], y, segColWidths, false);
    });
    y += 8;
  });

  // ── DATA VISUALIZATION ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Data Visualization', y, pageNum);
  y = bodyText(doc, `The dashboard contains ${charts.length} visualizations covering various chart types including ${[...new Set(charts.map((c) => c.type))].join(', ')}. These visualizations provide intuitive representations of the data, enabling quick identification of patterns, outliers, and relationships.`, y);
  y = bodyText(doc, 'The following chart types were utilized:', y);
  const chartTypeItems = [...new Set(charts.map((c) => c.type))].map((type) => {
    const count = charts.filter((c) => c.type === type).length;
    const descriptions = {
      kpi: 'Key metric cards showing aggregated values',
      bar: 'Bar charts for category-value comparison',
      'stacked-bar': 'Stacked bar charts for composition analysis',
      histogram: 'Histograms for distribution analysis',
      line: 'Line charts for trend visualization',
      area: 'Area charts for cumulative trends',
      step: 'Step charts for discrete changes',
      pie: 'Pie charts for proportional analysis',
      donut: 'Donut charts for composition breakdown',
      scatter: 'Scatter plots for correlation analysis',
      bubble: 'Bubble charts for multi-variable relationships',
      radar: 'Radar charts for multi-dimensional comparison',
      treemap: 'Treemaps for hierarchical proportion',
      funnel: 'Funnel charts for stage-wise progression',
      pareto: 'Pareto charts for 80/20 analysis',
      boxplot: 'Box plots for statistical distribution',
      heatmap: 'Heatmaps for intensity visualization',
      sankey: 'Sankey diagrams for flow analysis',
      table: 'Data tables for detailed inspection',
    };
    return `${type} (${count} chart${count > 1 ? 's' : ''}): ${descriptions[type] || 'Custom visualization'}`;
  });
  y = bulletList(doc, chartTypeItems, y, pageNum);

  // ── DASHBOARD ANALYSIS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Dashboard Analysis', y, pageNum);
  y = bodyText(doc, `The dashboard was configured with ${charts.length} widgets organized into Key Metrics (KPI cards), Analysis & Insights (charts), and Data Preview sections. The layout provides a top-down information flow: summary metrics at the top, detailed charts in the middle, and raw data at the bottom.`, y);
  const kpiCount = charts.filter((c) => c.type === 'kpi').length;
  const chartCount = charts.filter((c) => c.type !== 'kpi' && c.type !== 'table').length;
  const tableCount = charts.filter((c) => c.type === 'table').length;
  y = bodyText(doc, `Widget distribution: ${kpiCount} KPI card(s), ${chartCount} analytical chart(s), and ${tableCount} data table(s).`, y);
  y = bodyText(doc, 'The dashboard enables interactive exploration through filtering, chart editing, layout customization, and export capabilities. Users can add new charts, modify existing ones, and save the dashboard configuration as a reusable template.', y);

  // ── KEY FINDINGS / INSIGHTS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Key Findings / Insights', y, pageNum);
  y = bodyText(doc, 'The following key findings emerged from the analysis:', y);
  const findings = [];

  // Finding 1: Data overview
  findings.push(`The dataset contains ${totalRows.toLocaleString()} records with ${totalCols} variables, achieving ${completeness}% data completeness.`);

  // Finding 2: Top numeric metric
  if (numericCols.length > 0) {
    const col = numericCols[0];
    const values = data.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
    if (values.length > 0) {
      const total = values.reduce((a, b) => a + b, 0);
      const avg = total / values.length;
      findings.push(`${col.key} totals ${formatNumber(total)} with an average of ${formatNumber(avg)} per record, ranging from ${formatNumber(Math.min(...values))} to ${formatNumber(Math.max(...values))}.`);
    }
  }

  // Finding 3: Dominant category
  if (categoryCols.length > 0) {
    const col = categoryCols[0];
    const freq = {};
    data.forEach((r) => {
      const v = String(r[col.key] || '');
      if (v) freq[v] = (freq[v] || 0) + 1;
    });
    const top = Object.entries(freq).sort((a, b) => b[1] - a[1])[0];
    if (top) {
      findings.push(`"${top[0]}" is the dominant value in ${col.key}, representing ${((top[1] / totalRows) * 100).toFixed(1)}% of all records.`);
    }
  }

  // Finding 4: Trend
  if (dateCols.length > 0 && numericCols.length > 0) {
    const dateCol = dateCols[0];
    const numCol = numericCols[0];
    const sorted = [...data].sort((a, b) => new Date(a[dateCol.key]) - new Date(b[dateCol.key]));
    const values = sorted.map((r) => parseFloat(r[numCol.key])).filter((n) => !isNaN(n));
    if (values.length >= 4) {
      const mid = Math.floor(values.length / 2);
      const firstHalf = values.slice(0, mid).reduce((a, b) => a + b, 0) / mid;
      const secondHalf = values.slice(mid).reduce((a, b) => a + b, 0) / (values.length - mid);
      const change = firstHalf !== 0 ? ((secondHalf - firstHalf) / Math.abs(firstHalf)) * 100 : 0;
      findings.push(`${numCol.key} shows a ${change > 5 ? 'significant increase' : change < -5 ? 'significant decrease' : 'relatively stable'} trend (${change > 0 ? '+' : ''}${change.toFixed(1)}%) over the time period covered by ${dateCol.key}.`);
    }
  }

  // Finding 5: Correlation
  if (numericCols.length >= 2) {
    const c1 = numericCols[0];
    const c2 = numericCols[1];
    const pairs = data.map((r) => [parseFloat(r[c1.key]), parseFloat(r[c2.key])]).filter(([a, b]) => !isNaN(a) && !isNaN(b));
    if (pairs.length > 5) {
      const mean1 = pairs.reduce((s, p) => s + p[0], 0) / pairs.length;
      const mean2 = pairs.reduce((s, p) => s + p[1], 0) / pairs.length;
      const cov = pairs.reduce((s, p) => s + (p[0] - mean1) * (p[1] - mean2), 0) / pairs.length;
      const std1 = Math.sqrt(pairs.reduce((s, p) => s + (p[0] - mean1) ** 2, 0) / pairs.length);
      const std2 = Math.sqrt(pairs.reduce((s, p) => s + (p[1] - mean2) ** 2, 0) / pairs.length);
      const corr = std1 > 0 && std2 > 0 ? cov / (std1 * std2) : 0;
      const strength = Math.abs(corr) > 0.7 ? 'strong' : Math.abs(corr) > 0.4 ? 'moderate' : 'weak';
      findings.push(`A ${strength} ${corr > 0 ? 'positive' : 'negative'} correlation (r=${corr.toFixed(2)}) exists between ${c1.key} and ${c2.key}.`);
    }
  }

  // Finding 6: Outliers
  if (numericCols.length > 0) {
    const col = numericCols[0];
    const values = data.map((r) => parseFloat(r[col.key])).filter((n) => !isNaN(n));
    if (values.length > 10) {
      const mean = values.reduce((a, b) => a + b, 0) / values.length;
      const std = Math.sqrt(values.map((v) => (v - mean) ** 2).reduce((a, b) => a + b, 0) / values.length);
      const outliers = values.filter((v) => std > 0 && Math.abs((v - mean) / std) > 2.5);
      if (outliers.length > 0) {
        findings.push(`${outliers.length} outlier value(s) were detected in ${col.key} (beyond 2.5 standard deviations from the mean of ${formatNumber(mean)}).`);
      }
    }
  }

  y = bulletList(doc, findings, y, pageNum);

  // ── BUSINESS RECOMMENDATIONS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Business Recommendations', y, pageNum);
  y = bodyText(doc, 'Based on the analytical findings, the following business recommendations are proposed:', y);
  const recommendations = [
    'Focus resources on the highest-performing segments identified in the category analysis, as they contribute disproportionately to total value.',
    'Investigate the root causes of outlier values to determine whether they represent data quality issues or genuine business anomalies requiring attention.',
    'Leverage the identified temporal trends for forecasting and capacity planning, particularly for metrics showing significant upward or downward movement.',
    'Use the correlation insights to build predictive models — strongly correlated variables can serve as proxies or leading indicators for business outcomes.',
    'Address data completeness gaps by implementing validation rules at data entry points to reduce missing values in future collections.',
    'Segment-specific strategies should be developed for underperforming categories to understand barriers and identify improvement opportunities.',
    'Regularly monitor the KPIs identified in this report and set up automated alerts for significant deviations from expected ranges.',
  ];
  y = bulletList(doc, recommendations, y, pageNum);

  // ── CONCLUSION ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Conclusion', y, pageNum);
  y = bodyText(doc, `This analysis of the "${dataset?.name}" dataset revealed ${findings.length} key insights across ${numericCols.length} numeric and ${categoryCols.length} categorical dimensions. The data shows ${completeness}% completeness, indicating ${completeness > 95 ? 'high' : completeness > 80 ? 'moderate' : 'low'} data quality. The findings provide a foundation for data-driven decision-making, with clear opportunities for optimization across multiple segments and time periods.`, y);
  y = bodyText(doc, 'The combination of statistical analysis, visual exploration, and segment comparison has yielded actionable insights that can directly inform business strategy. The recommendations outlined above should be prioritized based on organizational goals and resource availability.', y);

  // ── LIMITATIONS ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Limitations', y, pageNum);
  y = bodyText(doc, 'The following limitations should be considered when interpreting the results of this analysis:', y);
  const limitations = [
    'The analysis is based solely on the provided dataset and does not incorporate external data sources or market context.',
    'Correlation does not imply causation — the relationships identified require further investigation to establish causal links.',
    'The automatic column type detection may misclassify columns with ambiguous data patterns, potentially affecting analysis accuracy.',
    `Missing values (${nullCounts.toLocaleString()} total) were excluded from calculations, which may introduce bias if the missingness is not random.`,
    'The analysis assumes the dataset is representative of the broader population; sampling biases may affect generalizability.',
    'Time-based trend analysis assumes chronological ordering and regular intervals; irregular time series may produce misleading trends.',
  ];
  y = bulletList(doc, limitations, y, pageNum);

  // ── FUTURE SCOPE ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Future Scope', y, pageNum);
  y = bodyText(doc, 'The following areas are recommended for future analysis and enhancement:', y);
  const futureScope = [
    'Integrate additional data sources (e.g., market data, customer demographics) to enrich the analysis and enable cross-domain insights.',
    'Apply machine learning models (clustering, regression, classification) to predict outcomes and identify hidden patterns.',
    'Implement real-time data pipelines for continuous monitoring and alerting on key metrics.',
    'Conduct A/B testing to validate the business recommendations and measure their impact.',
    'Develop interactive what-if analysis tools to simulate the effect of different business decisions.',
    'Expand the analysis to include sentiment analysis, geospatial mapping, and natural language processing where applicable.',
    'Set up automated report generation on a recurring schedule (daily, weekly, monthly) for ongoing monitoring.',
  ];
  y = bulletList(doc, futureScope, y, pageNum);

  // ── TOOLS & TECHNOLOGIES ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Tools & Technologies', y, pageNum);
  y = bodyText(doc, 'This analysis was conducted using the following tools and technologies:', y);
  const tools = [
    'DataVision AI Dashboard — Automated data analysis and visualization platform',
    'React.js — Frontend user interface framework',
    'Recharts — Charting and data visualization library',
    'PapaParse — CSV file parsing',
    'SheetJS (xlsx) — Excel file parsing',
    'jsPDF — PDF report generation',
    'html2canvas — Dashboard screenshot capture',
    'Zustand — State management',
    'IndexedDB — Client-side data persistence',
    'Vite — Build tool and development server',
  ];
  y = bulletList(doc, tools, y, pageNum);

  // ── APPENDIX ──
  doc.addPage();
  pageNum++;
  y = MARGIN;
  y = sectionTitle(doc, 'Appendix', y, pageNum);
  y = bodyText(doc, 'Appendix A: Full Data Dictionary', y, { fontSize: 12 });
  y += 4;
  const apColWidths = [120, 60, 70, 70, 70, CONTENT_WIDTH - 390];
  y = tableRow(doc, ['Column', 'Type', 'Min', 'Max', 'Avg', 'Nulls'], y, apColWidths, true);
  schema.forEach((col) => {
    if (y > PAGE_HEIGHT - MARGIN - 20) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
    y = tableRow(doc, [
      col.key.slice(0, 20),
      col.type,
      col.min !== null ? formatNumber(col.min) : '—',
      col.max !== null ? formatNumber(col.max) : '—',
      col.avg !== null ? formatNumber(col.avg) : '—',
      String(col.nullCount || 0),
    ], y, apColWidths, false);
  });

  y += 12;
  if (y > PAGE_HEIGHT - 100) { doc.addPage(); pageNum++; y = MARGIN; addPageNumber(doc, pageNum); }
  y = bodyText(doc, 'Appendix B: Statistical Summary', y, { fontSize: 12 });
  y += 2;
  y = bodyText(doc, `Total rows: ${totalRows.toLocaleString()}`, y, { fontSize: 10 });
  y = bodyText(doc, `Total columns: ${totalCols}`, y, { fontSize: 10 });
  y = bodyText(doc, `Numeric columns: ${numericCols.length}`, y, { fontSize: 10 });
  y = bodyText(doc, `Categorical columns: ${categoryCols.length}`, y, { fontSize: 10 });
  y = bodyText(doc, `Date columns: ${dateCols.length}`, y, { fontSize: 10 });
  y = bodyText(doc, `Missing values: ${nullCounts.toLocaleString()} (${(100 - completeness).toFixed(1)}%)`, y, { fontSize: 10 });
  y = bodyText(doc, `Data completeness: ${completeness}%`, y, { fontSize: 10 });
  y = bodyText(doc, `Dashboard widgets: ${charts.length}`, y, { fontSize: 10 });

  // Add footer to all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    addFooter(doc);
  }

  // Save
  const fileName = `${dataset?.name || 'Analysis'}_Report.pdf`;
  doc.save(fileName);
}
